# Generated by Django 5.0.7 on 2025-03-12 19:48

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_appointment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="address",
            field=models.CharField(
                default="FAST University", help_text="office address", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="contact_email1",
            field=models.EmailField(
                default="support@docucare.com",
                help_text="Application contact email 1",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="contact_email2",
            field=models.EmailField(
                default="support@docucare.com",
                help_text="Application contact email 2",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="contact_phone1",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+923360220224",
                help_text="Application contact phone 1",
                max_length=128,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="contact_phone2",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+923360220224",
                help_text="Application contact phone 2",
                max_length=128,
                region=None,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="name",
            field=models.CharField(
                default="FAST University", help_text="Application name", max_length=100
            ),
        ),
    ]
